apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "checkvatid.name" . }}
  labels:
    {{- include "checkvatid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "checkvatid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "checkvatid.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
          - containerPort: 80
