apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkvatid 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkvatid
  template:
    metadata:
      labels:
        app: checkvatid 
    spec:
      containers:
        - name: checkvatid 
          image: acrPaul.azurecr.io/checkvatid:31
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: checkvatid
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: checkvatid
