apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback 
    spec:
      containers:
        - name: feedback 
          image: acrPaul.azurecr.io/feedback
          ports:
          - containerPort: 80