apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback 
    spec:
      containers:
        - name: feedback 
          image: acrJenkinsAzure.azurecr.io/feedback:latest
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: feedback
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: feedback