apiVersion: apps/v1
kind: Deployment
metadata:
  name: getappinfo 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: getappinfo
  template:
    metadata:
      labels:
        app: getappinfo
    spec:
      containers:
        - name: getappinfo
          image: acrJenkinsAzure.azurecr.io/getappinfo:latest
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: getappinfo
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: getappinfo